### ISSUE TITLE
Some errors with some podcasts

### ISSUE THREAD

**Issue by gerroon** [raptor2101/PodCatcher#7]
I get some errors and empty folders with some podcasts. SOme come up empty, some throws alot of errors etc. It might give you some idea hopefully. 

I am on Debian Testing X64 using Kodi 16

20:14:44 T:140127888185088  NOTICE: [PodCatcher]: http://escapepod.org/2015/09/14/fan-film-review-star-trek-renegades/
20:14:44 T:140127888185088  NOTICE: [PodCatcher]: Downloading from url=http://escapepod.org/2015/09/14/fan-film-review-star-trek-renegades/
^C20:14:45 T:140127888185088  NOTICE: [PodCatcher]: Error while parsing item: <item>
                                            		<title>Fan Film Review: Star Trek: Renegades</title>
                                            		<link>http://escapepod.org/2015/09/14/fan-film-review-star-trek-renegades/</link>
                                            		<pubDate>Mon, 14 Sep 2015 14:00:46 +0000</pubDate>
                                            		<dc:creator><![CDATA[Josh Roseman]]></dc:creator>
                                            				<category><![CDATA[Reviews]]></category>
                                            		<category><![CDATA[adrienne wilkinson]]></category>
                                            		<category><![CDATA[edward furlong]]></category>
                                            		<category><![CDATA[fan film]]></category>
                                            		<category><![CDATA[grant imahara]]></category>
                                            		<category><![CDATA[hidden frontier]]></category>
                                            		<category><![CDATA[highlander 2]]></category>
                                            		<category><![CDATA[invictus]]></category>
                                            		<category><![CDATA[of gods and men]]></category>
                                            		<category><![CDATA[pavel chekov]]></category>
                                            		<category><![CDATA[renegades]]></category>
                                            		<category><![CDATA[sean young]]></category>
                                            		<category><![CDATA[section 31]]></category>
                                            		<category><![CDATA[star trek]]></category>
                                            		<category><![CDATA[star trek: renegades]]></category>
                                            		<category><![CDATA[tim russ]]></category>
                                            		<category><![CDATA[tuvok]]></category>
                                            		<category><![CDATA[walter koenig]]></category>
                                            
                                            		<guid isPermaLink="false">http://escapepod.org/?p=5234</guid>
                                            		<description><![CDATA[After the success of <i>Of Gods and Men</i>, Tim Russ returns to the fan film arena with <i>Star Trek: Renegades</i>. Though I had high expectations, I think I expected more than what I got. Especially from the writing.]]></description>
                                            		</item>
20:14:45 T:140127888185088  NOTICE: [PodCatcher]: Exception:
20:14:45 T:140127888185088   ERROR: Traceback (most recent call last):
20:14:45 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/rss.py", line 67, in updateFeed
20:14:45 T:140127888185088   ERROR:     feedItem.link = self.parseIndirectItem(self.readText(itemNode,"link"));
20:14:45 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/__init__.py", line 259, in parseIndirectItem
20:14:45 T:140127888185088   ERROR:     link = regex_mediaLink.search(htmlPage).group();
20:14:45 T:140127888185088   ERROR: AttributeError: 'NoneType' object has no attribute 'group'
20:14:45 T:140127888185088  NOTICE: [PodCatcher]: Stacktrace:
20:14:45 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/default.py", line 106, in <module>
20:14:45 T:140127888185088   ERROR:     opmlFile.displayMenu(path);
20:14:45 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/opml.py", line 150, in displayMenu
20:14:45 T:140127888185088   ERROR:     self.opmlFolder.displayMenu(path);
20:14:45 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/opml.py", line 72, in displayMenu
20:14:45 T:140127888185088   ERROR:     element.displayMenu(path);
20:14:45 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/__init__.py", line 142, in displayMenu
20:14:45 T:140127888185088   ERROR:     self.loadFeed();
20:14:45 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/__init__.py", line 134, in loadFeed
20:14:45 T:140127888185088   ERROR:     self.updateFeed();
20:14:45 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/rss.py", line 98, in updateFeed
20:14:45 T:140127888185088   ERROR:     traceback.print_stack();
20:14:45 T:140127888185088  NOTICE: [PodCatcher]: http://escapepod.org/2015/09/07/book-review-the-shepherds-crown-by-terry-pratchett/
20:14:45 T:140127888185088  NOTICE: [PodCatcher]: Downloading from url=http://escapepod.org/2015/09/07/book-review-the-shepherds-crown-by-terry-pratchett/
20:14:46 T:140127888185088  NOTICE: [PodCatcher]: Error while parsing item: <item>
                                            		<title>Book Review: The Shepherd’s Crown by Terry Pratchett</title>
                                            		<link>http://escapepod.org/2015/09/07/book-review-the-shepherds-crown-by-terry-pratchett/</link>
                                            		<pubDate>Mon, 07 Sep 2015 14:00:57 +0000</pubDate>
                                            		<dc:creator><![CDATA[Josh Roseman]]></dc:creator>
                                            				<category><![CDATA[Books]]></category>
                                            		<category><![CDATA[Reviews]]></category>
                                            		<category><![CDATA[agnes nitt]]></category>
                                            		<category><![CDATA[anagramma]]></category>
                                            		<category><![CDATA[ankh-morpork]]></category>
                                            		<category><![CDATA[archchancellor]]></category>
                                            		<category><![CDATA[death]]></category>
                                            		<category><![CDATA[discworld]]></category>
                                            		<category><![CDATA[dr. bustle]]></category>
                                            		<category><![CDATA[elves]]></category>
                                            		<category><![CDATA[geoffrey swivel]]></category>
                                            		<category><![CDATA[granny weatherwax]]></category>
                                            		<category><![CDATA[history monks]]></category>
                                            		<category><![CDATA[horace the cheese]]></category>
                                            		<category><![CDATA[i aten't dead]]></category>
                                            		<category><![CDATA[magrat]]></category>
                                            		<category><![CDATA[mephistopheles]]></category>
                                            		<category><![CDATA[mrs. earwig]]></category>
                                            		<category><![CDATA[nac mac feegle]]></category>
                                            		<category><![CDATA[nanny ogg]]></category>
                                            		<category><![CDATA[petulia]]></category>
                                            		<category><![CDATA[ponder stibbons]]></category>
                                            		<category><![CDATA[Terry Pratchett]]></category>
                                            		<category><![CDATA[the chalk]]></category>
                                            		<category><![CDATA[the patrician]]></category>
                                            		<category><![CDATA[the shepherd's crown]]></category>
                                            		<category><![CDATA[tiffany aching]]></category>
                                            		<category><![CDATA[wentworth]]></category>
                                            
                                            		<guid isPermaLink="false">http://escapepod.org/?p=5225</guid>
                                            		<description><![CDATA[On September 1, my Kindle automatically downloaded my preordered copy of <a href="http://amzn.to/1NZYcAy" target="_blank"><i>The Shepherd's Crown</i></a>. By September 3, I'd finished reading the final Discworld novel. Now the book is closed on the Discworld, at least in this form, and... well... I don't think I can wrap my head around that.]]></description>
                                            		</item>
20:14:46 T:140127888185088  NOTICE: [PodCatcher]: Exception:
20:14:46 T:140127888185088   ERROR: Traceback (most recent call last):
20:14:46 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/rss.py", line 67, in updateFeed
20:14:46 T:140127888185088   ERROR:     feedItem.link = self.parseIndirectItem(self.readText(itemNode,"link"));
20:14:46 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/__init__.py", line 259, in parseIndirectItem
20:14:46 T:140127888185088   ERROR:     link = regex_mediaLink.search(htmlPage).group();
20:14:46 T:140127888185088   ERROR: AttributeError: 'NoneType' object has no attribute 'group'
20:14:46 T:140127888185088  NOTICE: [PodCatcher]: Stacktrace:
20:14:46 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/default.py", line 106, in <module>
20:14:46 T:140127888185088   ERROR:     opmlFile.displayMenu(path);
20:14:46 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/opml.py", line 150, in displayMenu
20:14:46 T:140127888185088   ERROR:     self.opmlFolder.displayMenu(path);
20:14:46 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/opml.py", line 72, in displayMenu
20:14:46 T:140127888185088   ERROR:     element.displayMenu(path);
20:14:46 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/__init__.py", line 142, in displayMenu
20:14:46 T:140127888185088   ERROR:     self.loadFeed();
20:14:46 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/__init__.py", line 134, in loadFeed
20:14:46 T:140127888185088   ERROR:     self.updateFeed();
20:14:46 T:140127888185088   ERROR:   File "/home/xxx/.kodi/addons/plugin.audio.podcatcher/feedreader/rss.py", line 98, in updateFeed
20:14:46 T:140127888185088   ERROR:     traceback.print_stack();
20:14:46 T:140127888185088  NOTICE: [PodCatcher]: http://escapepod.org/2015/09/01/artemis-rising-returns/
20:14:46 T:140127888185088  NOTICE: [PodCatcher]: Downloading from url=http://escapepod.org/2015/09/01/artemis-rising-returns/
^C

**Comment by raptor2101** [comment]
Sorry for my late answer, i was busy.

These errors aper, i the podcatcher try to access a site without Media linked.

I've make a few changes to handle that

**Comment by gerroon** [comment]
thanks, keep the bug updated please.

**Comment by raptor2101** [comment]
can you test the fix please if its work on your side?
